[package]
name = "heroApi"
version = "0.1.0"
authors = ["ZiJiaW <964513305@qq.com>"]
edition = "2018"

[dependencies]
rocket = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rocket_contrib = { version = "0.4.0", features = ["json", "diesel_mysql_pool"] }
diesel = "1.4.2"